# SPDX-FileCopyrightText: 2018-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only
codecov:
  branch: master
  ci:
    - drone.nextcloud.com
  notify:
    after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.5

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
  require_changes: true
  after_n_builds: 2

github_checks:
    annotations: false

ignore:
  - "app/src/main/res/values*/*"

