# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: "Assemble"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: assemble-flavors-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    flavor:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                flavor: [ Generic, Gplay, Huawei ]
        steps:
            -   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            -   name: set up JDK 17
                uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Build ${{ matrix.flavor }}
                run: |
                    echo "org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g" >> gradle.properties
                    echo "org.gradle.caching=true" >> gradle.properties
                    echo "org.gradle.parallel=true" >> gradle.properties
                    echo "org.gradle.configureondemand=true" >> gradle.properties
                    echo "kapt.incremental.apt=true" >> gradle.properties
                    ./gradlew assemble${{ matrix.flavor }}
