# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: Check

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: check-kotlin-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck ]
        steps:
            -   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            -   name: Set up JDK 17
                uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Check ${{ matrix.task }}
                run: ./gradlew ${{ matrix.task }}
